# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ac2afe5eb0598c77b4040249a7157d0306fa8fb180c5b057d31fe5c8437784b8ed1c708e895387da26fa1c154e541279c20932e5c9b3b5452e5d508c66b711

test:
  secret_key_base: 9bddff02dc57cca539b6cdece79af6af94b1486ee300082b9c77b46b250479e01349e340d92513e0e84ceb80b5d9ba142bf0268a437aa46357a80762d9de25fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
